source("scripts/timeseries_csse_covid19_tidy_script.R")
source("scripts/timeseries_csse_covid19_dailyconfirmed_script.R")
source("scripts/timeseries_csse_covid19_dailydeath_script.R")
source("scripts/timeseries-csse-daily-confirmed-ggplot.R")
source("scripts/timeseries-csse-daily-deaths-ggplot.R")
